version: '3.7'
services:
  ryu-app-mysql8:
    container_name: ryu-app-mysql8
    image: mysql/mysql-server:8.0.23
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: develop
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: ryu-app-mysql8
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ryu-app-db-data:/var/lib/mysql
    ports:
      - '3306:3306'
    env_file:
      - .development.env
volumes:
  ryu-app-db-data:
